project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: About
        icon: info-circle
        menu:
          - text: Information for sponsors
            href: info-spon.qmd
  page-footer:
    center: © UNSW 2023

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
