project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: Information for sponsors
        icon: info-circle
        href: sponsor-info.qmd

  page-footer:
    center: © UNSW 2023

format:
  html:
    css: styles.css
    theme:
      dark: solar
      light: sandstone
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
