project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: Schedule
        icon: clock
        href: schedule.qmd
      - text: Data
        icon: code
        href: data.qmd
      - text: Judging Criteria
        icon: trophy
        href: judging-criteria.qmd
      - text: Code of conduct
        icon: heart
        href: code-of-conduct.qmd
      - text: 2023 Highlights
        icon: balloon-heart-fill
        href: review.qmd
    right:
      - text: Information for sponsors
        icon: info-circle
        href: sponsor-info.qmd
      - text: Demo
        icon: fire
        href: demo.qmd

  page-footer:
    center: © UNSW 2023

format:
  html:
    css: styles.css
    theme:
      dark: solar
      light: [sandstone, theme-dark.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
